lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '#)"/9]8T,CM~^w2.z!$'
    token_ttl:        3600
    user_identity_field: email
